### ISSUE TITLE
Activation of MS Office failed

### ISSUE THREAD

**Issue by Saeedjaanz** [khaouitiabdelhakim/Microsoft-Office-With-Activation-For-Lifetime#2]
Hey, Thankyou for providing the solution to MS office's activation. So I run the process as given by you in the repository, followed the guidelines perfectly. But at the end while running "Activator.bat" as "Run as administrator", there my activation got failed.

I am providing a snapshot of the cmd console for more information here. So please help me out here. I wanna activate my office for lifetime.
<img width="960" alt="Capture" src="https://github.com/khaouitiabdelhakim/Microsoft-Office-With-Activation-For-Lifetime/assets/134127527/8493d45e-df14-4a51-804e-f2996d831dbe">

**Comment by khaouitiabdelhakim** [comment]
Hey bro, have you install the office following the commands in my repo, or you are trying to activate an installer version on your computer?

**Comment by khaouitiabdelhakim** [comment]
?
